version: '3'
services:
  wordpress:
    image: wordpress:5.2-php7.3-fpm-alpine
    depends_on:
      - wordpress_database
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRES_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"

  wordpress_database:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: my_wordpress_password

  wordpress_webserver:
    image: nginx:1.14-alpine
    depends_on:
      - wordpress
    volumes:
      - ./docker/wordpress/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - wordpress_data:/var/www/html
    ports:
      - 80:80

  wordpress_toolbox:
    build: ./docker/wordpress/toolbox/
    volumes:
      - wordpress_data:/wordpress
    working_dir: /wordpress
    depends_on:
      - wordpress_database
    environment:
      WORDDPRESS_LOCALE: "${WORDPRESS_LOCALE}"
      # WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      # WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
      # WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      # WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_WEBSITE_TITLE: "${WORDPRESS_WBSITE_TITLE}"
      WORDPRESS_WEBSITE_URL: "${WORDPRESS_WEBSITE_URL}"
      WORDPRESS_WEBSITE_URL_WITHOUT_HTTP: "${WORDPRESS_WEBSITE_URL_WITHOUT_HTTP}"
      WORDPRESS_WEBSITE_POST_URL_STRUCTURE: "/%year%/%monthnum%/%day%/%postname%/"
      WORDPRESS_ADMIN_USER: "${WORDPRESS_ADMIN_USER}"
      WORDPRESS_ADMIN_PASSWORD: "${WORDPRESS_ADMIN_PASSWORD}"

volumes:
  db_data: {}
  wordpress_data: {}
